panier:
    pattern:  /
    defaults: { _controller: EcommerceBundle:Panier:panier }

livraison:
    pattern:  /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    pattern:  /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }